from models.funcionarios import funcionario

funcionario1 = funcionario("Carlos", "1111111111", "Operador CNC", 4500)
funcionario2 = funcionario("João", "2222222222", "Programador CNC", 6000)
funcionario3 = funcionario("Maria", "3333333333", "Engenheira de Produção", 8000)
funcionario4 = funcionario("Ana", "4444444444", "Gerente de Produção", 10000)
print("\n=================================")
print("Informações dos Funcionários:")
print("=================================\n")
print(funcionario1.nome)
print(funcionario1.cpf)
print(funcionario1.cargo)
print(funcionario1.salario)
print("\n=================================\n")
print(funcionario2.nome)
print(funcionario2.cpf)
print(funcionario2.cargo)
print(funcionario2.salario)
print("\n=================================\n")
print(funcionario3.nome)
print(funcionario3.cpf)
print(funcionario3.cargo)
print(funcionario3.salario)
print("\n=================================\n")
print(funcionario4.nome)
print(funcionario4.cpf)
print(funcionario4.cargo)
print(funcionario4.salario)
print("\n=================================\n")